title: awesome
author: Jimmymok
email: jimmymok7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
---
title: "hi"
date: 2022-04-10
---

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
